[package]
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Parallel iterator processing"
documentation = "https://docs.rs/pariter"
edition = "2018"
homepage = "https://github.com/dpc/pariter"
keywords = ["parallel", "iterator", "parallel_map"]
license = "MPL-2.0 OR MIT OR Apache-2.0"
name = "pariter"
readme = "README.md"
repository = "https://github.com/dpc/pariter"
version = "0.5.1"

[[bench]]
harness = false
name = "bench"

[dependencies]
flume = { version = "0.11", default-features = false }
num_cpus = "1.13"

[dev-dependencies]
criterion = "0.5"
quickcheck = "1"
quickcheck_macros = "1"

[package.metadata.release]
pre-release-replacements = [
  { file = "CHANGELOG.md", search = "Unreleased", replace = "{{version}}", min = 1 },
  { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
  { file = "CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}", min = 1 },
  { file = "CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n## [Unreleased](https://github.com/dpc/pariter/compare/{{tag_name}}...HEAD) - ReleaseDate\n\n", exactly = 1 },
]
shared-version = true
